# Use the official MySQL image as the base image
FROM mysql:latest

# Set environment variables for the root password, database name, user, and password
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=humanresources-db
ENV MYSQL_USER=my_user
ENV MYSQL_PASSWORD=user_password

# Expose the MySQL port (optional)
EXPOSE 3306
